#!/usr/bin/env bash

BASE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
LOG=post-setup-apply.log
cd $BASE_DIR

echo "$(date) - Post-setup apply" > $LOG
env >> $LOG
echo "$(date) - Post-setup apply" >> $LOG

# if [[ "$_COMMENT"  == "" ]]; then
#   _COMMENT="Comment missing"
# fi
# if [[ "$_USER" == "" ]]; then
#   _USER="unknown"
# fi
# if [[ "$_WORKSTATION" == "" ]]; then
#   _WORKSTATION="unknown"
# fi
# w=$_WORKSTATION
# fu=$_USER
# su=${fu#*\\}

# if [[ ! -e .git ]]; then 
#    git init > /dev/null
# fi

# echo "$_COMMENT" > comment.txt
# echo "$_FILES" > file-info.xml

# git add *.xml  */*.xml > /dev/null

# git commit --file=comment.txt --author="$fu <$su@$w>" > /dev/null
# rm comment.txt

# ver=`git log --format="%h" -n 1`
# echo "<setup><files>"
# for f in $( ls *.xml */*.xml); do
# 	echo "<file><path>$f</path><version>$ver</version></file>"
# done
# echo "</files></setup>"
