#!/usr/bin/env bash

BASE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
cd $BASE_DIR

#echo "Validate setup"

env > validate.log

echo "<validation><issues>"
echo "<issue><severity>Critical</severity><path>/gateway/operatingEnvironment/httpConnectionRequirements</path><message>Custom critical validation error</message></issue>"
echo "<issue><severity>Warning</severity><path>/gateway/operatingEnvironment/httpConnectionRequirements</path><message>Custom warning validation error</message></issue>"

echo "</issues></validation>"
